### ISSUE TITLE
Add ability to filter filters by OS support

### ISSUE THREAD

**Issue by mallman** [DavidWingate/CIFilterBox#8]
I like to identify the filters added in releases of macOS. It would be helpful to be able to filter the list of filters by OS version.

**Comment by DavidWingate** [comment]
I have implemented a rudimentary results filter, it works for CICategories as well as macOS and iOS versions. It also lists any custom categories added so you can see just those filters. It will be included in the next release (should be within a couple of weeks). Thanks for the suggestion!

**Comment by DavidWingate** [comment]
New version including this feature has been accepted by the App Store. Should be available for update shortly.
